[package]
name = "uisp"
version = "0.1.0"
edition = "2021"

[dependencies]
lqos_config = { path = "../lqos_config" }
serde = { workspace = true }
reqwest = { workspace = true }
anyhow = { workspace = true }
