[package]
name = "uisp"
version = "0.1.0"
edition = "2024"

[dependencies]
lqos_config = { path = "../lqos_config" }
serde = { workspace = true }
reqwest = { workspace = true }
anyhow = { workspace = true }
# For memory debugging
allocative.workspace = true
allocative_derive.workspace = true