use allocative::Allocative;
use serde::{Deserialize, Serialize};
use strum::{Display, EnumIter, EnumString};

#[derive(
    PartialEq,
    Clone,
    Copy,
    Debug,
    EnumIter,
    Display,
    EnumString,
    Hash,
    Eq,
    Allocative,
    Serialize,
    Deserialize,
)]
pub enum PublishedChannels {
    /// Provides a 1-second tick notification to the client
    Cadence,
    Throughput,
    Retransmits,
    RttHistogram,
    FlowCount,
    TopDownloads,
    TopUploads,
    WorstRTT,
    WorstRetransmits,
    TopFlowsBytes,
    TopFlowsRate,
    EndpointsByCountry,
    FlowDurations,
    EtherProtocols,
    IpProtocols,
    Cpu,
    Ram,
    TreeSummary,
    TreeSummaryL2,
    QueueStatsTotal,
    NetworkTree,
    NetworkTreeClients,
    CircuitCapacity,
    TreeCapacity,
    StormguardStatus,
    StormguardDebug,
    BakeryStatus,
    EndpointLatLon,
    AsnTopDownload,
    AsnTopUpload,
    ExecutiveHeatmaps,
}
