[package]
name = "lqos_node_manager"
version = "0.2.0"
edition = "2021"
license = "GPL-2.0-only"

[features]
default = ["equinix_tests"]
equinix_tests = []

[dependencies]
askama = "0.12.0"
async-channel = "1.8.0"
async-redis-session = "0.2.2"
async-trait = "0.1.68"
axum = { version = "0.6.15", features = ["headers", "multipart", "tracing", "ws"] }
axum-login = { version = "0.4.1" }
axum-server = { version = "0.4.7", features = ["tls-rustls"] }
dashmap = "5"
dns-lookup = "1"
enum_dispatch = "0.3.11"
eyre = { version = "0.6.8", default-features = false }
futures = "0.3.28"
futures-util = { version = "0.3.28", default-features = false, features = ["sink", "std"] }
headers = "0.3.8"
lazy_static = "1.4"
parking_lot = "0.12"
rand = { version = "0.8.5", features = ["min_const_gen"] }
redis = "*"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
tokio = { version = "1.27.0", features = ["rt-multi-thread"] }
tokio-stream = "0.1.12"
tokio-tungstenite = "0.18.0"
tower = { version = "0.4", features = ["util", "timeout"] }
tower-http = { version = "0.4", features = ["cors", "fs", "trace", "compression-gzip"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
uuid = { version = "1.3.1", features = ["v4", "serde" ] }

lqos_bus = { path = "../lqos_bus" }
lqos_config = { path = "../lqos_config" }
lqos_utils = { path = "../lqos_utils" }
anyhow = "1"
sysinfo = "0"
default-net = "0"
nix = "0"
once_cell = "1"

# Support JemAlloc on supported platforms
[target.'cfg(any(target_arch = "x86", target_arch = "x86_64"))'.dependencies]
jemallocator = "0.5"