[package]
name = "lqos_bakery"
version = "0.1.0"
edition = "2024"

[dependencies]
lqos_config = { path = "../lqos_config" }
anyhow.workspace = true
tracing.workspace = true
crossbeam-channel.workspace = true
