/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function connect_wasm_pipe(a: number, b: number): void;
export function is_wasm_connected(): number;
export function send_wss_queue(): void;
export function send_token(a: number, b: number): void;
export function send_login(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function request_node_status(): void;
export function request_packet_chart(a: number, b: number): void;
export function request_packet_chart_for_node(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function request_throughput_chart(a: number, b: number): void;
export function request_throughput_chart_for_site(a: number, b: number, c: number, d: number): void;
export function request_throughput_chart_for_node(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function request_throughput_chart_for_circuit(a: number, b: number, c: number, d: number): void;
export function request_site_stack(a: number, b: number, c: number, d: number): void;
export function request_rtt_chart(a: number, b: number): void;
export function request_rtt_chart_for_site(a: number, b: number, c: number, d: number): void;
export function request_rtt_chart_for_node(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function request_rtt_chart_for_circuit(a: number, b: number, c: number, d: number): void;
export function request_node_perf_chart(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function request_root_heat(a: number, b: number): void;
export function request_site_heat(a: number, b: number, c: number, d: number): void;
export function request_tree(a: number, b: number): void;
export function request_site_info(a: number, b: number): void;
export function request_site_parents(a: number, b: number): void;
export function request_circuit_parents(a: number, b: number): void;
export function request_root_parents(): void;
export function request_search(a: number, b: number): void;
export function request_circuit_info(a: number, b: number): void;
export function request_ext_device_info(a: number, b: number): void;
export function request_ext_snr_graph(a: number, b: number, c: number, d: number): void;
export function request_ext_capacity_graph(a: number, b: number, c: number, d: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hb4b341652e081e3f(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__ha318d2d73313995c(a: number, b: number, c: number): void;
export function __wbindgen_free(a: number, b: number): void;
export function __wbindgen_exn_store(a: number): void;
