/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function initialize_wss(a: number, b: number): void;
export function is_wasm_connected(): number;
export function send_wss_queue(): void;
export function send_token(a: number, b: number): void;
export function send_login(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function request_node_status(): void;
export function request_packet_chart(a: number, b: number): void;
export function request_packet_chart_for_node(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function request_throughput_chart(a: number, b: number): void;
export function request_throughput_chart_for_site(a: number, b: number, c: number, d: number): void;
export function request_throughput_chart_for_node(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function request_throughput_chart_for_circuit(a: number, b: number, c: number, d: number): void;
export function request_site_stack(a: number, b: number, c: number, d: number): void;
export function request_rtt_chart(a: number, b: number): void;
export function request_rtt_histogram(a: number, b: number): void;
export function request_rtt_chart_for_site(a: number, b: number, c: number, d: number): void;
export function request_rtt_chart_for_node(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function request_rtt_chart_for_circuit(a: number, b: number, c: number, d: number): void;
export function request_node_perf_chart(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function request_root_heat(a: number, b: number): void;
export function request_site_heat(a: number, b: number, c: number, d: number): void;
export function request_tree(a: number, b: number): void;
export function request_site_info(a: number, b: number): void;
export function request_site_parents(a: number, b: number): void;
export function request_circuit_parents(a: number, b: number): void;
export function request_root_parents(): void;
export function request_search(a: number, b: number): void;
export function request_circuit_info(a: number, b: number): void;
export function request_ext_device_info(a: number, b: number): void;
export function request_ext_snr_graph(a: number, b: number, c: number, d: number): void;
export function request_ext_capacity_graph(a: number, b: number, c: number, d: number): void;
export function __wbindgen_export_0(a: number): number;
export function __wbindgen_export_1(a: number, b: number, c: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function __wbindgen_export_3(a: number, b: number, c: number): void;
export function __wbindgen_export_4(a: number, b: number): void;
export function __wbindgen_export_5(a: number): void;
